# Generated by Django 4.2.8 on 2024-01-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=70)),
                ('name_news', models.TextField(max_length=60)),
                ('date_news', models.DateField()),
            ],
        ),
    ]
